{"level":"error","message":"uncaught Exception: connect ETIMEDOUT 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: MongoServerError: cannot find user account after reload"}
{"level":"error","message":"uncaught Exception: MongoServerError: cannot find user account after reload"}
{"level":"error","message":"uncaught Exception: MongoServerError: cannot find user account after reload"}
{"level":"error","message":"uncaught Exception: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/"}
{"level":"error","message":"uncaught Exception: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/"}
{"level":"error","message":"uncaught Exception: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/"}
{"level":"error","message":"uncaught Exception: MongoServerError: bad auth : Authentication failed."}
{"level":"error","message":"uncaught Exception: MongoServerError: bad auth : Authentication failed."}
{"level":"error","message":"uncaught Exception: MongoServerError: bad auth : Authentication failed."}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: [Poru Websocket] Unable to connect with v1 node after 5 tries"}
{"level":"error","message":"unhandled Rejection: Cannot read properties of undefined (reading 'resolve')"}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: [Poru Websocket] Unable to connect with v1 node after 5 tries"}
{"level":"error","message":"unhandled Rejection: other side closed"}
{"level":"error","message":"uncaught Exception: connect ECONNREFUSED 176.31.203.30:3625"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
{"level":"error","message":"uncaught Exception: ENOENT: no such file or directory, scandir 'C:\\Users\\felic\\Documents\\Github\\PancyBot\\src\\temp\\images'"}
